<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 카테고리 조회 (존재하지 않으면 예외 발생)
        $categories = [
            '미백' => ProductCategory::where('slug', 'whitening')->firstOrFail()->id,
            '잇몸케어' => ProductCategory::where('slug', 'gum-care')->firstOrFail()->id,
            '민감치아' => ProductCategory::where('slug', 'sensitive')->firstOrFail()->id,
            '어린이' => ProductCategory::where('slug', 'kids')->firstOrFail()->id,
            '한방' => ProductCategory::where('slug', 'herbal')->firstOrFail()->id,
            '토탈케어' => ProductCategory::where('slug', 'total-care')->firstOrFail()->id,
        ];

        $products = [
            // 미백 치약
            [
                'name' => 'Dr.Smile 프리미엄 미백치약',
                'slug' => 'premium-whitening-toothpaste',
                'sku' => 'DSTP-001',
                'price' => 12900,
                'original_price' => 15900,
                'cost_price' => 5000,
                'category_id' => $categories['미백'],
                'brand' => 'Dr.Smile',
                'description' => '천연 미백 성분으로 치아를 밝게 가꿔주는 프리미엄 미백치약입니다.',
                'short_description' => '자연스러운 미백 효과',
                'ingredients' => '정제수, 소르비톨, 탄산칼슘, 실리카, 라우릴황산나트륨, 향료',
                'efficacy' => '치아 미백, 충치 예방, 구취 제거',
                'usage_instructions' => '적당량을 칫솔에 묻혀 2-3분간 칫솔질하세요.',
                'precautions' => '6세 이하 어린이는 보호자 지도 하에 사용하세요.',
                'volume' => '120g',
                'features' => ['미백', '불소함유', '저자극'],
                'target_audience' => ['성인'],
                'rating' => 4.7,
                'review_count' => 892,
                'stock' => 500,
                'sold_count' => 3421,
                'is_active' => true,
                'is_best_seller' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0001호',
                'manufacturer' => 'Dr.Smile 제약',
                'distributor' => 'Dr.Smile Corp.',
                'published_at' => now(),
            ],
            [
                'name' => 'Dr.Smile 화이트닝 파워 치약',
                'slug' => 'whitening-power-toothpaste',
                'sku' => 'DSTP-002',
                'price' => 14900,
                'original_price' => 17900,
                'cost_price' => 6000,
                'category_id' => $categories['미백'],
                'brand' => 'Dr.Smile',
                'description' => '강력한 미백 효과로 누런 치아를 밝게 만들어주는 화이트닝 치약입니다.',
                'short_description' => '강력한 미백 파워',
                'efficacy' => '치아 미백, 얼룩 제거',
                'volume' => '120g',
                'features' => ['강력미백', '불소함유', '민트향'],
                'target_audience' => ['성인'],
                'rating' => 4.5,
                'review_count' => 543,
                'stock' => 300,
                'sold_count' => 1876,
                'is_active' => true,
                'is_featured' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0002호',
                'published_at' => now(),
            ],

            // 잇몸케어 치약
            [
                'name' => 'Dr.Smile 잇몸케어 치약',
                'slug' => 'gum-care-toothpaste',
                'sku' => 'DSTP-003',
                'price' => 9900,
                'cost_price' => 4000,
                'category_id' => $categories['잇몸케어'],
                'brand' => 'Dr.Smile',
                'description' => '약해진 잇몸을 강화하고 잇몸 출혈을 예방하는 치약입니다.',
                'short_description' => '건강한 잇몸 관리',
                'efficacy' => '잇몸 출혈 예방, 잇몸 강화, 치석 제거',
                'volume' => '120g',
                'features' => ['잇몸강화', '출혈예방', '한방성분'],
                'target_audience' => ['성인', '노인'],
                'rating' => 4.6,
                'review_count' => 567,
                'stock' => 300,
                'sold_count' => 1987,
                'is_active' => true,
                'is_best_seller' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0003호',
                'published_at' => now(),
            ],

            // 민감치아 치약
            [
                'name' => 'Dr.Smile 민감치아 치약',
                'slug' => 'sensitive-toothpaste',
                'sku' => 'DSTP-004',
                'price' => 11900,
                'cost_price' => 4500,
                'category_id' => $categories['민감치아'],
                'brand' => 'Dr.Smile',
                'description' => '시린 이를 완화하고 민감한 치아를 보호하는 전문 치약입니다.',
                'short_description' => '시린 이 완화',
                'efficacy' => '시린 이 완화, 치아 보호막 형성',
                'volume' => '120g',
                'features' => ['민감완화', '저자극', '무연마제'],
                'target_audience' => ['성인'],
                'rating' => 4.7,
                'review_count' => 432,
                'stock' => 250,
                'sold_count' => 1543,
                'is_active' => true,
                'is_featured' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0004호',
                'published_at' => now(),
            ],

            // 어린이 치약
            [
                'name' => 'Dr.Smile 키즈 치약 (딸기향)',
                'slug' => 'kids-toothpaste-strawberry',
                'sku' => 'DSTP-005',
                'price' => 7900,
                'cost_price' => 3000,
                'category_id' => $categories['어린이'],
                'brand' => 'Dr.Smile',
                'description' => '불소 함유로 충치를 예방하고 아이들이 좋아하는 딸기향 치약입니다.',
                'short_description' => '딸기향 어린이 전용 치약',
                'efficacy' => '충치 예방, 치아 강화',
                'volume' => '80g',
                'features' => ['불소함유', '딸기향', '저불소'],
                'target_audience' => ['어린이'],
                'rating' => 4.8,
                'review_count' => 721,
                'stock' => 400,
                'sold_count' => 2876,
                'is_active' => true,
                'is_best_seller' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0005호',
                'published_at' => now(),
            ],
            [
                'name' => 'Dr.Smile 키즈 치약 (포도향)',
                'slug' => 'kids-toothpaste-grape',
                'sku' => 'DSTP-006',
                'price' => 7900,
                'cost_price' => 3000,
                'category_id' => $categories['어린이'],
                'brand' => 'Dr.Smile',
                'description' => '아이들이 좋아하는 포도향으로 즐겁게 양치질할 수 있습니다.',
                'short_description' => '포도향 어린이 전용 치약',
                'efficacy' => '충치 예방, 치아 강화',
                'volume' => '80g',
                'features' => ['불소함유', '포도향', '저불소'],
                'target_audience' => ['어린이'],
                'rating' => 4.7,
                'review_count' => 489,
                'stock' => 350,
                'sold_count' => 1932,
                'is_active' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0006호',
                'published_at' => now(),
            ],

            // 한방 치약
            [
                'name' => 'Dr.Smile 한방 치약',
                'slug' => 'herbal-toothpaste',
                'sku' => 'DSTP-007',
                'price' => 13900,
                'cost_price' => 5500,
                'category_id' => $categories['한방'],
                'brand' => 'Dr.Smile',
                'description' => '천연 한방 성분으로 만든 프리미엄 치약입니다.',
                'short_description' => '천연 한방 성분',
                'ingredients' => '정제수, 소르비톨, 탄산칼슘, 실리카, 녹차추출물, 자작나무추출물',
                'efficacy' => '구취 제거, 잇몸 강화, 치석 예방',
                'volume' => '120g',
                'features' => ['한방성분', '천연', '녹차추출물'],
                'target_audience' => ['성인'],
                'rating' => 4.5,
                'review_count' => 378,
                'stock' => 220,
                'sold_count' => 1234,
                'is_active' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0007호',
                'published_at' => now(),
            ],

            // 토탈케어 치약
            [
                'name' => 'Dr.Smile 토탈케어 치약',
                'slug' => 'total-care-toothpaste',
                'sku' => 'DSTP-008',
                'price' => 10900,
                'cost_price' => 4500,
                'category_id' => $categories['토탈케어'],
                'brand' => 'Dr.Smile',
                'description' => '미백, 잇몸케어, 충치예방을 한번에 해결하는 올인원 치약입니다.',
                'short_description' => '올인원 구강 케어',
                'efficacy' => '미백, 잇몸 케어, 충치 예방, 구취 제거',
                'volume' => '120g',
                'features' => ['올인원', '미백', '잇몸케어', '충치예방'],
                'target_audience' => ['성인'],
                'rating' => 4.6,
                'review_count' => 654,
                'stock' => 450,
                'sold_count' => 2543,
                'is_active' => true,
                'is_featured' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0008호',
                'published_at' => now(),
            ],
            [
                'name' => 'Dr.Smile 프리미엄 토탈케어',
                'slug' => 'premium-total-care-toothpaste',
                'sku' => 'DSTP-009',
                'price' => 15900,
                'original_price' => 18900,
                'cost_price' => 6500,
                'category_id' => $categories['토탈케어'],
                'brand' => 'Dr.Smile',
                'description' => '프리미엄 성분으로 구강 건강을 완벽하게 지켜주는 최상급 치약입니다.',
                'short_description' => '프리미엄 올인원 케어',
                'efficacy' => '미백, 잇몸 케어, 충치 예방, 구취 제거, 치석 예방',
                'volume' => '120g',
                'features' => ['프리미엄', '올인원', '미백', '잇몸케어'],
                'target_audience' => ['성인'],
                'rating' => 4.8,
                'review_count' => 432,
                'stock' => 200,
                'sold_count' => 1567,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0009호',
                'published_at' => now(),
            ],

            // 기타 토탈케어
            [
                'name' => 'Dr.Smile 센시티브 토탈케어',
                'slug' => 'sensitive-total-care-toothpaste',
                'sku' => 'DSTP-010',
                'price' => 12900,
                'cost_price' => 5200,
                'category_id' => $categories['토탈케어'],
                'brand' => 'Dr.Smile',
                'description' => '민감한 치아를 위한 저자극 토탈케어 치약입니다.',
                'short_description' => '민감치아용 토탈케어',
                'efficacy' => '시린 이 완화, 미백, 잇몸 케어, 충치 예방',
                'volume' => '120g',
                'features' => ['저자극', '민감완화', '올인원'],
                'target_audience' => ['성인'],
                'rating' => 4.6,
                'review_count' => 298,
                'stock' => 180,
                'sold_count' => 987,
                'is_active' => true,
                'is_quasi_drug' => true,
                'approval_number' => '제2024-0010호',
                'published_at' => now(),
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
